# Configuración de memoria para la compilación
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# Soporte para librerías modernas (AndroidX)
android.useAndroidX=true
android.enableJetifier=true

# Versiones y características
FLIPPER_VERSION=0.182.0
ReactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false
hermesEnabled=true

# ── Configuración de Compilación ──
enableProguardInReleaseBuilds=false

# ── Firma release ── (Placeholder para que no falle el build)
MYAPP_RELEASE_STORE_FILE=citofonia.keystore
MYAPP_RELEASE_KEY_ALIAS=citofonia
MYAPP_RELEASE_STORE_PASSWORD=CAMBIAR_ESTE_PASSWORD
MYAPP_RELEASE_KEY_PASSWORD=CAMBIAR_ESTE_PASSWORD
